services:
  tweetservice:
    image: ${DOCKER_REGISTRY-}tweetservice
    build:
      context: .
      dockerfile: TweetService/Dockerfile
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
  searchservice:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: SearchService/Dockerfile
  twitterapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: TwitterAPI/Dockerfile
  mssql:
     image: mcr.microsoft.com/mssql/server:2022-latest
     ports:
      - 1433:1433
     environment:
       MSSQL_SA_PASSWORD: "S3cr3tP4sSw0rd#123"
       ACCEPT_EULA: "Y"
     volumes:             
      - database-data:/var/opt/mssql

volumes:
 database-data:  
