services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - appnetwork

  tweetapi:
    image: ${DOCKER_REGISTRY-}tweetapi
    build:
      context: .
      dockerfile: TweetApi/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - apigateway
    networks:
      - appnetwork

  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - apigateway
    networks:
      - appnetwork

  searchapi:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: SearchApi/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - apigateway
    networks:
      - appnetwork

  authservice:
    image: authservice
    build: 
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "8085:8080"
    networks:
      - appnetwork

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "S3cr3tP4sSw0rd#123"
      ACCEPT_EULA: "Y"
    volumes:             
      - database-data:/var/opt/mssql
    networks:
      - appnetwork

volumes:
  database-data: 

networks:
  appnetwork:
    driver: bridge