services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
     - "8080:80"
  tweetapi:
    image: ${DOCKER_REGISTRY-}tweetapi
    build:
      context: .
      dockerfile: TweetApi/Dockerfile
    ports:
    - "8081:80"
    depends_on:
     - apigateway
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports:
    - "8082:80"
    depends_on:
     - apigateway
  searchapi:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: SearchApi/Dockerfile
    ports:
    - "8083:80"
    depends_on:
     - apigateway
  # twitterapi:
  #   image: ${DOCKER_REGISTRY-}userapi
  #   build:
  #     context: .
  #     dockerfile: TwitterAPI/Dockerfile
  #   ports:
  #   - "8084:80"
  #   depends_on:
  #    - apigateway
  authservice:
    image: authservice
    build: 
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
     - "8085:80"
  mssql:
     image: mcr.microsoft.com/mssql/server:2022-latest
     ports:
      - 1433:1433
     environment:
       MSSQL_SA_PASSWORD: "S3cr3tP4sSw0rd#123"
       ACCEPT_EULA: "Y"
     volumes:             
      - database-data:/var/opt/mssql

volumes:
 database-data:  
