apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: twitterclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: krazlo/authservice:latest
        ports:
        - containerPort: 8080
        env:
        volumeMounts:
        - name: logs
          mountPath: /var/log/app
      volumes:
      - name: logs
        emptyDir: {}