apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: twitterclone
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/*.log
      pos_file /var/log/app/fluentd.pos
      tag app.logs
      <parse>
        @type none
      </parse>
    </source>

    <match app.logs>
      @type file
      path /fluentd/log/output.log
      append true
    </match>