apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: twitterclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_SA_PASSWORD
          value: "S3cr3tP4sSw0rd#123"
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssql-data
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc