apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: twitterclone
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp-port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management-port
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP