apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  namespace: twitterclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: krazlo/userapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: logs
          mountPath: /var/log/app
      - name: fluentd
        image: fluent/fluentd:v1.14-1
        ports:
        - containerPort: 24224
        env:
        - name: FLUENTD_ARGS
          value: "--no-supervisor -c /fluentd/etc/fluent.conf"
        volumeMounts:
        - name: logs
          mountPath: /var/log/app
        - name: fluentd-config
          mountPath: /fluentd/etc
      volumes:
      - name: logs
        emptyDir: {}
      - name: fluentd-config
        configMap:
          name: fluentd-config